# Build script for msma 4.0.0
# Run this script from the directory containing src.r, DESCRIPTION,
# CITATION, NEWS.md, and (optionally) vignettes/msma.Rmd.

options(repos = c(CRAN = "https://cloud.r-project.org"))

package_name <- "msma"
package_version <- "4.0"
source_archive <- sprintf("%s_%s.tar.gz", package_name, package_version)
windows_archive <- sprintf("%s_%s.zip", package_name, package_version)

required_files <- c("src.r", "DESCRIPTION", "CITATION", "NEWS")
missing_files <- required_files[!file.exists(required_files)]
if (length(missing_files)) {
  stop("Missing required file(s): ", paste(missing_files, collapse = ", "))
}

build_packages <- c("roxygen2", "testthat", "knitr", "rmarkdown")
missing_packages <- build_packages[
  !vapply(build_packages, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_packages)) {
  install.packages(missing_packages, dependencies = TRUE)
}

still_missing <- build_packages[
  !vapply(build_packages, requireNamespace, logical(1), quietly = TRUE)
]
if (length(still_missing)) {
  stop(
    "The following build packages could not be installed: ",
    paste(still_missing, collapse = ", ")
  )
}

# Normalize and validate DESCRIPTION before creating the package.
desc_lines <- readLines("DESCRIPTION", warn = FALSE, encoding = "UTF-8")
desc_lines <- desc_lines[nzchar(trimws(desc_lines))]
desc_lines <- desc_lines[!grepl("^(Packaged|Repository|Date/Publication):", desc_lines)]
writeLines(desc_lines, "DESCRIPTION", useBytes = TRUE)

tryCatch(
  read.dcf("DESCRIPTION"),
  error = function(e) stop("Invalid DESCRIPTION file: ", conditionMessage(e))
)

# Load functions so package.skeleton() can collect the package objects.
source("src.r", local = .GlobalEnv)

# Remove previous build products.
if (dir.exists(package_name)) unlink(package_name, recursive = TRUE, force = TRUE)
for (f in c(source_archive, windows_archive)) {
  if (file.exists(f)) unlink(f, force = TRUE)
}

# Create the package skeleton from src.r.
utils::package.skeleton(
  name = package_name,
  code_files = "src.r",
  force = TRUE
)

# Remove files generated by package.skeleton that will be regenerated.
unlink(list.files(
  file.path(package_name, "man"),
  pattern = "[.]Rd$",
  full.names = TRUE
), force = TRUE)
unlink(file.path(package_name, "NAMESPACE"), force = TRUE)
unlink(file.path(package_name, "Read-and-delete-me"), force = TRUE)

# Restore canonical metadata before roxygenize(). package.skeleton() creates
# its own DESCRIPTION without the Encoding field.
file.copy("DESCRIPTION", file.path(package_name, "DESCRIPTION"), overwrite = TRUE)

# Generate documentation and NAMESPACE from the roxygen comments in src.r.
roxygen2::roxygenize(package_name)

# Re-copy package metadata in case a documentation tool updated it.
file.copy("DESCRIPTION", file.path(package_name, "DESCRIPTION"), overwrite = TRUE)
tryCatch(
  read.dcf(file.path(package_name, "DESCRIPTION")),
  error = function(e) stop("Invalid package DESCRIPTION: ", conditionMessage(e))
)
file.copy("NEWS", file.path(package_name, "NEWS"), overwrite = TRUE)

dir.create(file.path(package_name, "inst"), recursive = TRUE, showWarnings = FALSE)
file.copy("CITATION", file.path(package_name, "inst", "CITATION"), overwrite = TRUE)

# Copy tests if supplied with the development source.
if (dir.exists("tests")) {
  file.copy("tests", package_name, recursive = TRUE, overwrite = TRUE)
}

# Detect Pandoc. Copy vignettes only when they can be rendered.
pandoc_available <- rmarkdown::pandoc_available()
if (pandoc_available && dir.exists("vignettes")) {
  file.copy("vignettes", package_name, recursive = TRUE, overwrite = TRUE)
} else if (!pandoc_available) {
  message(
    "Pandoc was not found. Building the local source package without vignettes."
  )
  package_desc <- file.path(package_name, "DESCRIPTION")
  d <- readLines(package_desc, warn = FALSE)
  d <- d[!grepl("^VignetteBuilder:", d)]
  writeLines(d, package_desc, useBytes = TRUE)
}

# Build the source package. R CMD build creates msma_4.0.tar.gz.
build_args <- c("CMD", "build", package_name, "--force")
if (!pandoc_available) {
  build_args <- c(build_args, "--no-build-vignettes")
}
build_status <- system2(file.path(R.home("bin"), "R"), build_args)
if (build_status != 0L || !file.exists(source_archive)) {
  stop("R CMD build failed or did not create ", source_archive)
}

# Install the source package and run the test suite.
install_status <- system2(
  file.path(R.home("bin"), "R"),
  c("CMD", "INSTALL", source_archive)
)
if (install_status != 0L) stop("R CMD INSTALL failed")

# Run CRAN-style checks against the source archive.
check_args <- c("CMD", "check", "--as-cran")
if (!pandoc_available) {
  check_args <- c(check_args, "--ignore-vignettes")
}
check_args <- c(check_args, source_archive)
check_status <- system2(file.path(R.home("bin"), "R"), check_args)
if (check_status != 0L) {
  warning("R CMD check completed with a non-zero status. Review msma.Rcheck/00check.log")
}

# roxygen2 may have loaded the source-tree namespace before NAMESPACE was
# regenerated. Reload the newly installed package so post-build interactive
# tests see the current exports rather than that stale namespace.
if (package_name %in% loadedNamespaces()) {
  try(unloadNamespace(package_name), silent = TRUE)
}
installed_path <- find.package(package_name, lib.loc = .libPaths(), quiet = TRUE)
if (!nzchar(installed_path)) {
  stop("The newly installed package could not be located after the build")
}
loadNamespace(package_name, lib.loc = dirname(installed_path))
message("Reloaded installed namespace from: ", installed_path)

message("Build completed: ", normalizePath(source_archive, mustWork = FALSE))
message("Check log: ", normalizePath("msma.Rcheck/00check.log", mustWork = FALSE))


